name: gxbank_project
version: '1.0'
config-version: 2

profile: gxbank_profile

model-paths: ['models']
seed-paths: ['seeds']
target-path: 'target' # directory which will store compiled SQL files
clean-targets: ['target', 'dbt_modules'] # directories to be removed by `dbt clean`